### ISSUE TITLE
Hex web auth

### ISSUE THREAD

**Issue by starbelly** [erlef/gsoc#7]
**Description**

hex web auth flow

**Recommended Skills**

Erlang and elixir. The biggest chunk of work will require elixir skills, erlang is needed for hex_core and rebar3_hex

**Mentor(s)**

 - Bryan Paxton
 - Todd Resudek 

**Project URL(s)**

@pablocostass is to add this project to the wiki soon. Here is a link to the B&P action item for this project : https://github.com/erlef/build-and-packaging-wg/issues/21

**Comment by starbelly** [comment]
It should be noted that Todd's availablily is tentative, it depends on the timezone of the student(s) involved.

**Comment by pablocostass** [comment]
@starbelly @supersimple is this something that has been done already, or would you like to still propose this idea but for the current year (2022) in the case that we get accepted?

**Comment by supersimple** [comment]
Pablo, most of that work is already completed so we wouldn't want to submit
it this year.
Thanks,
TR
